name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies_01
      run: dotnet restore UnitTesting/Base.MVC/Base.MVC.csproj
    - name: Restore dependencies_02
      run: dotnet restore UnitTesting/BaseAPI/BaseAPI.csproj
    - name: Restore dependencies_03
      run: dotnet restore UnitTesting/BaseProject/BaseProject.csproj
    - name: Build_01
      run: dotnet build UnitTesting/Base.MVC/Base.MVC.csproj.csproj
    - name: Build_02
      run: dotnet build UnitTesting/BaseAPI/BaseAPI.csproj.csproj
    - name: Build_03
      run: dotnet build UnitTesting/BaseProject/BaseProject.csproj
#   - name: Test
#     run: dotnet test --no-build --verbosity normal
#    - name: Upload a Build Artifact
#     uses: actions/upload-artifact@v2.2.2
#     with:
#       name: api
#     path:  papasgrill.app
#     if-no-files-found: error
